import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/Shared/Footer";
import Nabvar from "@/components/Shared/Nabvar";
import AuthProvider from "@/services/AuthProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Doctor Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer />
        <AuthProvider>
          <Nabvar />
          <div>{children}</div>
         <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
